use qlsv
select 
*from sinhvien1
select 
*from MONHOC
select*from KQUA
select*from HOCPHAN
SELECT MAMH, TENMH, TINCHI, MH.MAKHOA, TENKHOA
FROM MONHOC MH, KHOA1 K
WHERE TENKHOA=N'Thống kê tin học' AND MH.MAKHOA=K.MAKHOA

select K.MAKHOA,TENKHOA,MAHP,TENMH
FROM KHOA1 K,HOCPHAN,MONHOC MH
WHERE MAHP='2111' AND HOCPHAN.MAMH=MH.MAMH AND MH.MAKHOA=K.MAKHOA

SELECT TENSV,SV.MASV,TENMH,HP.MAHP
FROM SINHVIEN1 SV, MONHOC MH, KQUA,HOCPHAN HP
WHERE TENMH=N'Cơ sở dữ liệu' and SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH


use qlsv
select 
*from sinhvien1
select 
*from MONHOC
SELECT*FROM KHOA1
select*from KQUA
select*from HOCPHAN
--QUAN HỆ THÔNG QUA KHÓA NGOẠI CHỖ MAKHOA
SELECT MAMH, TENMH, TINCHI, MH.MAKHOA, TENKHOA 
FROM MONHOC MH, KHOA1 K
WHERE TENKHOA=N'Thống kê tin học' AND MH.MAKHOA=K.MAKHOA


SELECT*
FROM MONHOC MH,KHOA1 K
WHERE K.MAKHOA=MH.MAKHOA AND TENKHOA=N'THỐNG KÊ TIN HỌC'

--BÀI TẬP 2: CHO BIẾT KHOA(MAKHOA,TENKHOA...) QUẢN LÝ HỌC PHẦN CSDL_2111
SELECT*
FROM MONHOC MH,KHOA1 K,HOCPHAN HP
WHERE MAHP='2111' AND K.MAKHOA=MH.MAKHOA AND HP.MAMH=MH.MAMH

--C2:
--SELECT K.MAKHOA,TENKHOA,HP.MAMH,TENMH
--JOIN PHÉP KẾT QUAN HỆ
SELECT K.MAKHOA,TENKHOA,HP.MAMH,TENMH
FROM (KHOA1 K JOIN MONHOC MH ON K.MAKHOA=MH.MAKHOA) JOIN HOCPHAN HP ON HP.MAMH=MH.MAMH
WHERE MAHP=2111

--BAI 3:TÌM NHỮNG SINH VIÊN ĐÃ HỌC MÔN CƠ SỞ DỮ LIỆU (TENSV,MASV)
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=N'Cơ sở dữ liệu' and SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH AND (DIEM>=5 AND DIEM<=9)
 
--GHI FROM VỚI WHERE TRƯỚC RỒI MỚI GHI SELECT(KẾT NỐI BẢNG NÀO VỚI BẢNG NÀO).KHÓA NGOẠI VỚI KHÓA CHÍNH KẾT NỐI VỚI NHAU
--MASV NẰM TRONG SINHVIEN HAY KQUA ĐỀU ĐƯỢC
--VIẾT HOA HAY THƯỜNG KHÔNG QUAN TRỌNG MIỄN NHẬP ĐÚNG--

--MỆNH ĐỀ WHERE
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=N'Cơ sở dữ liệu' and SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH AND DIEM BETWEEN 5 AND 9
--HOẶC NOT BETWEEN (NẰM NGOÀI ĐIỀU KIỆN)--
--TÌM SINH VIÊN CÓ HỌ LÀ NGUYỄN
SELECT*FROM SINHVIEN1 WHERE TENSV=N'NGUYỄN' --CHẮC CHẮN SAI VÀ KHÔNG RA KQ--
SELECT*FROM SINHVIEN1 WHERE TENSV LIKE N'NGUYỄN%' --TÌM HỌ--
SELECT*FROM SINHVIEN1 WHERE TENSV LIKE N'%BÌNH'--TÌM TÊN CUỐI--
SELECT*FROM SINHVIEN1 WHERE TENSV LIKE N'%THẾ%'--TÌM TÊN Ở GIỮA--
SELECT*FROM SINHVIEN1 WHERE TENSV NOT LIKE N'%THẾ%' --TÌM NHỮNG TÊN KHÔNG CÓ CHỮ THẾ--
--day,year,date,month,like,not like,chuyển ngày tháng năm qua năm tháng ngày--
--LẦN SAU LÀM BÀI TẬP NHIỀU NÊN CHÚ Ý XEM VIDEO--

--MỆNH ĐỀ ORDER BY--
SELECT*
FROM KHOA1

--PHÉP TOÁN TẬP HỢP --
/*
-UNION [ALL]: HỢP
-INTERSECT [ALL]: GIAO
-EXCEPT [ALL]: TRỪ*/
--TRUY VẤN 1 <PHÉP TOÁN TẬP HỢP> TRUY VẤN 2.SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
--TÌM NHỮNG SINH VIÊN HỌC MÔN CƠ SỞ LẬP TRÌNH    --TÌM NHỮNG SINH VIÊN HỌC MÔN CƠ SỞ LẬP TRÌNH
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=N'Cơ sở dữ liệu' AND DIEM>7 and SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
UNION
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH AND TENMH=N'Cơ Sở Lập Trình'
--TRÊN KIA BAO NHIÊU THUỘC TÍNH THÌ DƯỚI NI BẤY NHIÊU THUỘC TÍNH
--bài 1: cho biết sinh viên chưa học môn cơ sở dữ liệu
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
EXCEPT
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
--TRUY VẤN TẬP HỢP LÀ TRUY VẤN CHẬM NHẤT NÊN KHÔNG GỌI LÀ TRUY VẤN ĐẸP, LỰA CHỌN TRUY VẤN NÀO CŨNG ĐƯỢC MIỄN RA KẾT QUẢ--
--TUẦN SAU LÀM QUA BÀI TẬP QUẢN LÝ NHÂN VIÊN--

--TRUY VẤN LỒNG---
--LỒNG PHÂN CẤP
--QUERY CHA VÀ QUERY CON--
/*SELECT..
  FROM...
  WHERE. TT.. <BIỂU THỨC KẾT NỐI> 
              <S..
			  W
			  O
--1 TT THÌ BÊN BIỂU THỨC KẾT NỐI CÓ 1 TT, 2 TT THÌ BÊN BIỂU THỨC KẾT NỐI CÓ 2 TT
--KIỂM TRA CON TRƯỚC
--IN TƯƠNG ĐƯƠNG DẤU BẰNG, NOT IN TƯƠNG ĐƯƠNG DẤU TRỪ, ALL, SOME, ANY
PHÂN LỒNG TƯƠNG QUAN THÌ BIỂU THỨC KẾT NỐI LÀ EXIST AND NOT EXIST .KTRA TOÀN BỘ QH CON CÓ TỒN TẠI TRONG TRUY VẤN CHA HAY KHÔNG.CON LẤY TT CỦA CHA ĐỂ TRUY VẤN 
BTAP: CHO BIẾT SINH VIÊN CHƯA HỌC MÔN CƠ SỞ DỮ LIỆU*/

SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
EXCEPT
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH

SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
AND SV.MASV NOT IN
    (SELECT SV.MASV
	FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
	WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH)

SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
AND NOT EXISTS
    (SELECT *
	FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
	WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH)
--BÀI NOT EXISTS KHÔNG CHẠY RA ĐƯỢC VÌ PHẢI DÙNG JOIN--
--KHÔNG CÓ SỰ KẾT NỐI NÊN KHÔNG RA ĐƯỢC KẾT QUẢ--
--JOIN ON XONG TẤT CẢ CÁC CÁI NỚ--
--LỒNG TƯƠNG QUAN ÍT SỬ DỤNG, CHỈ DỤNG TRONG PHÉP CHIA (SV HỌC TẤT CẢ CÁC HỌC PHẦN(NÂNG CAO))--
--VỀ NHÀ LÀM CHƯƠNG 4  (GIẢI 2.1,2.2,2.4 (PHÉP KẾT VÀ PHÉP LỒNG))
--TÌM MỘT NHÂN VIÊN CÓ LƯƠNG LỚN HƠN PHÒNG NGHIÊN CỨU
--TÌM MỘT SINH VIÊN ĐÃ CÓ ĐIỂM LỚN HƠN BẠN ĐÃ HỌC CSDL--
--LÀM BÀI TẬP CHƯƠNG 4.1 VÀ CHƯƠNG 4.2 SẼ THI ĐƯỢC GIỮA KÌ--

--TÌM NHỮNG SINH VIÊN KHÔNG HỌC MÔN CƠ SỞ DỮ LIỆU ( BẰNG 2 CÁCH)
--C1: EXCEPT
--C2: NOT IN
--C3: NOT EXIST

--CÁCH 1:
select 
*from sinhvien1
select 
*from MONHOC
select*from KQUA
select*from HOCPHAN
select*from KHOA1
select*from DIEUKIEN
--CÁCH 1:
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
EXCEPT
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
--CÁCH 2:
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
AND SV.MASV NOT IN
    (SELECT SV.MASV
	FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
	WHERE TENMH=(N'Cơ sở dữ liệu') AND SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH)
--CÁCH 3:
SELECT TENSV,SV.MASV,TENMH,HP.MAHP,DIEM
FROM SINHVIEN1 SV, MONHOC MH,KQUA,HOCPHAN HP
WHERE SV.MASV=KQUA.MASV AND KQUA.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH
AND NOT EXISTS
    (SELECT *
	FROM (SINHVIEN1 SV JOIN KQUA KQ ON SV.MASV=KQUA.MASV) JOIN HOCPHAN HP ON KQUA.MAHP=HP.MAHP JOIN MONHOC MH ON MH.MAMH=HP.MAMH
	WHERE TENMH=(N'Cơ sở dữ liệu')
	)