create DATABASE QLTP

create table KHACHTHUE
(
MAKH varchar(10) not null,
HOTEN NVARCHAR(50) NOT NULL,
NGAYSINH DATETIME,
SODT VARCHAR (10) NOT NULL, 
CCCD varchar (15) not null,
CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)
create table CANHO
(
MAPHG NVARCHAR(10) NOT NULL,
DIENTICH INT,
GIATHUE INT,
CONSTRAINT PK_PHG PRIMARY KEY(MAPHG)
)
CREATE TABLE THUEPHONG
(
MAKH VARCHAR(10) UNIQUE NOT NULL,
MAPHG NVARCHAR(10) NOT NULL,
NGAYBD DATETIME,
NGAYKT DATETIME,
CONSTRAINT PK_MAKH PRIMARY KEY(MAKH),
CONSTRAINT U_MAKH UNIQUE(MAKH),
CONSTRAINT FK_TP_KH FOREIGN KEY(MAKH) REFERENCES KHACHTHUE(MAKH),
CONSTRAINT FK_TP_PHG FOREIGN KEY(MAPHG) REFERENCES CANHO(MAPHG)
)
--CÂU 2:--
select MAKH,HOTEN,YEAR(GETDATE())-YEAR(NGAYSINH) TUỔI
from KHACHTHUE
where HOTEN LIKE N'NGUYỄN%' AND (YEAR(GETDATE())-YEAR(NGAYSINH)>=30)

--CÂU 3:--
SELECT KT.MAKH,HOTEN,NGAYSINH,SODT,CCCD,(MONTH(NGAYKT)-MONTH(NGAYBD)) AS THANGTHUE
FROM KHACHTHUE KT,THUEPHONG TP
WHERE KT.MAKH=TP.MAKH
--Câu 4:--
UPDATE THUEPHONG
SET THANHTIEN = GiaThue * DATEDIFF(MONTH,NGAYBD,NGAYKT)
FROM CANHO CH INNER JOIN THUEPHONG TP ON CH.MAPHG = TP.MAPHG
--Câu 5:--
select MAKH,HOTEN,DIENTICH
from CANHO,KHACHTHUE
where DIENTICH=60 or DIENTICH=90

--Câu 6:--
SELECT KT.MAKH,HOTEN, MONTH(NGAYKT)-MONTH(NGAYBD) AS 'THANG THUE'
FROM KHACHTHUE KT, CANHO CH,THUEPHONG TP
WHERE KT.MAKH=TP.MAKH AND CH.MAPHG=TP.MAPHG AND (MONTH(NGAYKT)-MONTH(NGAYBD)BETWEEN 1 AND 6 AND YEAR(NGAYKT)-YEAR(NGAYBD)= '2022')
--Câu 7:--
SELECT MAPHG,GIATHUE
FROM CANHO
EXCEPT
SELECT CH.MAPHG,GIATHUE
FROM CANHO CH, THUEPHONG TP,KHACHTHUE KT
WHERE CH.MAPHG=TP.MAPHG AND KT.MAKH=TP.MAKH
--Câu 8:--
SELECT KT.MAKH,HOTEN,SUM(GIATHUE) 'TỔNG TIỀN THUÊ',COUNT(TP.MAKH)'SỐ LẦN THUÊ'
FROM KHACHTHUE KT,CANHO CH,THUEPHONG TP
WHERE KT.MAKH=TP.MAKH AND CH.MAPHG=TP.MAPHG
GROUP BY KT.MAKH,HOTEN


--CÂU 9:--
select top 3 MAKH,HOTEN,SUM(GIATHUE) 'TỔNG TIỀN THUÊ CĂN HỘ'
FROM KHACHTHUE,CANHO
GROUP by MAKH,HOTEN
ORDER BY GIATHUE DESC


--CÂU 10:--
ALTER TABLE CANHO ADD LOAIPHG NVARCHAR(20)
UPDATE CANHO
SET LOAIPHG=
CASE
	WHEN DIENTICH=40 THEN N'PHONGNHO'
	WHEN DIENTICH=60 THEN N'PHONGTB'
	WHEN DIENTICH=90 THEN N'PHONGLON'
END

