--BUỔI 12/10
USE QLSV
--CAC THAO TAC TREN BANG
--CAC THAO TAC VOI DL
/*CHINH SUA BANG CHON LENH: ALTER TABLE
XOA: DROP TABLE/COLUMN*/
-- THEM COT VAO BANG
ALTER TABLE SINHVIEN ADD 
SODT varchar(15),
DCHI nvarchar(50)
GO
-- THEM RANG BUOC TOAN VEN
-- ALTER  TABLE <TENBANG> ADD CONSTRAINT PK_BANG PRIMARY KEY(TEN THUOC TINH) -> RBTV VE KHOA CHINH
/*ALTER TABLE <TENBANG> ADD CONSTRAINT FK_BANGCHINH_BANGTC
FOREIGN KEY(TENTT) REFERENCES BANG1(FK_bang1)
--DEFAULT, CHECK, UNIQUE, NOT NULL*/
ALTER TABLE SINHVIEN ADD 
CONSTRAINT CHK_SODT CHECK (LEN(SODT)=10)

ALTER TABLE SINHVIEN ADD
CONSTRAINT DF_SV

--SUA COT
ALTER TABLE SINHVIEN ALTER COLUMN DCHI VARCHAR(100)
--XOA COT
ALTER TABLE SINHVIEN DROP COLUMN DCHI
ALTER TABLE SINHVIEN DROP COLUMN SODT



--BUỔI 19/10
--1.TÌM TẤT CẢ SINH VIÊN THUỘC KHOA CÓ MÃ KHOA LÀ TKTH
SELECT *
FROM SINHVIEN1
SELECT*
FROM SINHVIEN1
WHERE MAKHOA='TKTH'

DELETE FROM SINHVIEN1 WHERE MASV='SV0012'
--TÌM TẤT CẢ SINH VIÊN (MASV,TENSV,NAM) THUỘC KHOA CÓ MÃ KHOA LÀ TKTH

SELECT MASV,TENSV,NAM
FROM SINHVIEN1
WHERE MAKHOA='TKTH'

--ĐẶT BÍ DANH CHO THUỘC TÍNH
SELECT MASV AS 'MÃ SINH VIÊN',TENSV 'TÊN SINH VIÊN', NAM 'NĂM NHẬP HỌC'
FROM SINHVIEN1
WHERE MAKHOA='TKTH'

--2.TÌM TẤT CẢ SINH VIÊN(MASV,TENSV,NAM) THUỘC KHOA CÓ MÃ KHOA LÀ TKTH VÀ --MASV LÀ SV001
SELECT MASV AS 'MÃ SINH VIÊN', TENSV 'TÊN SINH VIÊN', NAM 'NĂM NHẬP HỌC'
FROM SINHVIEN1
WHERE MAKHOA='TKTH' AND MASV='SV001'
--4.TÌM TẤT CẢ SINH VIÊN(MASV,TENSV,NAM) THUỘC KHOA CÓ MÃ KHOA LÀ TKTH VÀ HOẶC LÀ SINH VIÊN NĂM 2
SELECT MASV AS 'MÃ SINH VIÊN', TENSV 'TÊN SINH VIÊN', NAM 'NĂM NHẬP HỌC',MAKHOA
FROM SINHVIEN1
WHERE(MAKHOA='TKTH'AND MASV='SV001') OR NAM=2
SELECT*FROM SINHVIEN1


--TÌM KHOA (MAKHOA,TENKHOA,SONAM) CÓ SỐ NĂM TL >=20
SELECT MAKHOA 'MÃ KHOA', TENKHOA 'TÊN KHOA', NAMTL'SỐ NĂM THÀNH LẬP'
FROM KHOA1
WHERE NAMTL>=20

ALTER TABLE KHOA1 DROP COLUMN NAMTL

--MUỐN THÊM LẠI THÌ 
SELECT MAKHOA 'MÃ KHOA', TENKHOA 'TÊN KHOA', (YEAR(GETDATE())-NAMTL) 'SỐ NĂM'
FROM KHOA1
WHERE YEAR(GETDATE())-NAMTL>=20

USE QLNV
SELECT MANV,HONV,TENLOT,MLUONG
FROM NHANVIEN

SELECT MANV, HONV +' '+ TENLOT, MLUONG,MLUONG*0.05
FROM NHANVIEN


--DISTINCT LOẠI BỎ TRÙNG LẶP--
SELECT DISTINCT TENSV
FROM SINHVIEN1
WHERE MAKHOA='TKTH'
--PHÉP KẾT TRONG
--CÁCH 1:
SELECT MASV,TENSV,TENKHOA
FROM SINHVIEN1,KHOA1
WHERE TENKHOA=N'THÔNG KÊ TIN HỌC' AND MAKHOA=MAKHOA

--sẽ bị lỗi vì nó không hiểu mã khoa nằm ở bảng nào.--

SELECT MASV,TENSV,TENKHOA
FROM SINHVIEN1,KHOA1
WHERE TENKHOA=N'THÔNG KÊ TIN HỌC' AND SINHVIEN1.MAKHOA=KHOA1.MAKHOA

--CÁCH 2:
SELECT MASV,SV.MAKHOA,TENSV,TENKHOA
FROM SINHVIEN1 SV,KHOA1 K
WHERE TENKHOA=N'THỐNG KÊ TIN HỌC' AND SV.MAKHOA=K.MAKHOA

--INNER JOIN NÓ KẾT LUÔN--
--CÁCH 3:
SELECT MASV,SV.MAKHOA,TENSV,TENKHOA
FROM SINHVIEN1 SV INNER JOIN KHOA K ON SV.MAKHOA=K.MAKHOA
WHERE TENKHOA=N'THỐNG KÊ TIN HỌC' AND SV.MAKHOA=K.MAKHOA







