create database KHACHHANG
create table KHACHHANG
(
MAKH VARCHAR(10) UNIQUE NOT NULL,
HOTEN NVARCHAR(50) NOT NULL,
DCHI NVARCHAR(100) NOT NULL,
SODIENTHOAI VARCHAR (10) NOT NULL, 
NGSINH DATETIME,
PHAI NVARCHAR (8) NOT NULL,
)
create table NHANVIEN
(
MANV VARCHAR(10) UNIQUE NOT NULL,
HOTEN NVARCHAR(50) NOT NULL,
DCHI NVARCHAR(100) NOT NULL,
SODIENTHOAI VARCHAR(10) NOT NULL,
NGAYSINH DATETIME,
PHAI NVARCHAR(8) NOT NULL,
)
create table SANPHAM
(
MASP VARCHAR(10) UNIQUE NOT NULL,
TENSP NVARCHAR(50) NOT NULL,
NUOCSX NVARCHAR(15) NOT NULL, 
GIA INT,
)
create table HOADON
(
SOHD varchar(10) not null,
NGHD datetime,
SOLUONG INT,
MASP VARCHAR (10) NOT NULL,
MAKH VARCHAR(10)  NOT NULL,
MANV VARCHAR(10) NOT NULL,
)
alter table HOADON ADD MANV VARCHAR(10)
ALTER TABLE HOADON ADD MAKH VARCHAR(10)
DROP TABLE HOADON

--Câu 3--:
select PHAI,DCHI,YEAR(GETDATE())-YEAR(NGSINH) TUỔI
from KHACHHANG
WHERE (YEAR(GETDATE())-YEAR(NGSINH))>=40 AND DCHI LIKE N'%TP HỒ CHÍ MINH'

--CÂU 4--:
SELECT SP.MASP,TENSP,NGHD
FROM HOADON HD, SANPHAM SP
WHERE NGHD LIKE N'%2022/8' AND HD.MASP=SP.MASP

--CÂU 5:--
SELECT NUOCSX,MANV,HOTEN,GIA
FROM SANPHAM SP, NHANVIEN NV
WHERE NUOCSX=N'%VIỆT NAM' OR NUOCSX=N'%TRUNG QUỐC' AND GIA>=500.000

--CÂU 6:--
Select top 1 MASP,TENSP,GIA
From SANPHAM
order by GIA DESC

--CÂU 7:--
SELECT HOTEN,SP.MASP,TENSP,NGHD
FROM NHANVIEN NV,HOADON HD, SANPHAM SP
WHERE SP.MASP=HD.MASP
EXCEPT
SELECT HOTEN,SP.MASP,TENSP,NGHD
FROM NHANVIEN NV,HOADON HD, SANPHAM SP
WHERE SP.MASP=HD.MASP AND  NV.MANV=HD.MANV and HOTEN=N'NGUYỄN VĂN A' 

SELECT MASP,TENSP
FROM SANPHAM
EXCEPT
SELECT SP.MASP,TENSP
FROM  NHANVIEN NV, SANPHAM SP, HOADON HD
WHERE NV.MANV=HD.MANV AND SP.MASP=HD.MASP AND HOTEN=N'NGUYỄN VĂN A'

--CÂU 8--

FROM KHACHHANG KH, 